<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle"
     style="display:inline-block;width:<?php echo $this->ad->getWidth(); ?>px;height:<?php echo $this->ad->getHeight(); ?>px"
     data-ad-client="ca-<?php echo $this->ad->getPartnerId(); ?>"
     data-ad-slot="<?php echo $this->ad->getId(); ?>"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>